service: jarvis-ai-q

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  timeout: 30
  memorySize: 512

functions:
  jarvis:
    handler: lambda_handler.lambda_handler
    events:
      - http:
          path: /jarvis
          method: post
          cors: true
      - http:
          path: /jarvis
          method: get
          cors: true

plugins:
  - serverless-python-requirements